let north_america = [
  "The Bahamas",
  "Belize",
  "Canada",
  "Costa Rica",
  "Cuba",
  "Dominican Republic",
  "Greenland",
  "Guatemala",
  "Honduras",
  "Haiti",
  "Iceland",
  "Jamaica",
  "Mexico",
  "Nicaragua",
  "Panama",
  "Puerto Rico",
  "El Salvador",
  "USA"
]

let europe = [
  "Albania",
  "Austria",
  "Azerbaijan",
  "Belgium",
  "Bulgaria",
  "Bosnia and Herzegovina",
  "Belarus",
  "Switzerland",
  "Northern Cyprus",
  "Cyprus",
  "Czech Republic",
  "Germany",
  "Denmark",
  "Spain",
  "Estonia",
  "Finland",
  "France",
  "England",
  "Georgia",
  "Greece",
  "Croatia",
  "Hungary",
  "Ireland",
  "Italy",
  "Kazakhstan",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Moldova",
  "Macedonia",
  "Montenegro",
  "Netherlands",
  "Norway",
  "Portugal",
  "Romania",
  "Russia",
  "Republic of Serbia",
  "Slovakia",
  "Slovenia",
  "Sweden",
  "Turkey",
  "Ukraine",
  "Poland"
]

let countries = [
  "Afghanistan",
  "Angola",
  "Albania",
  "United Arab Emirates",
  "Argentina",
  "Armenia",
  "Antarctica",
  "French Southern and Antarctic Lands",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Burundi",
  "Belgium",
  "Benin",
  "Burkina Faso",
  "Bangladesh",
  "Bulgaria",
  "The Bahamas",
  "Bosnia and Herzegovina",
  "Belarus",
  "Belize",
  "Bolivia",
  "Brazil",
  "Brunei",
  "Bhutan",
  "Botswana",
  "Central African Republic",
  "Canada",
  "Switzerland",
  "Chile",
  "China",
  "Ivory Coast",
  "Cameroon",
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Northern Cyprus",
  "Cyprus",
  "Czech Republic",
  "Germany",
  "Djibouti",
  "Denmark",
  "Dominican Republic",
  "Algeria",
  "Ecuador",
  "Egypt",
  "Eritrea",
  "Spain",
  "Estonia",
  "Ethiopia",
  "Finland",
  "Fiji",
  "Falkland Islands",
  "France",
  "Gabon",
  "England",
  "Georgia",
  "Ghana",
  "Guinea",
  "Gambia",
  "Guinea Bissau",
  "Equatorial Guinea",
  "Greece",
  "Greenland",
  "Guatemala",
  "Guyana",
  "Honduras",
  "Croatia",
  "Haiti",
  "Hungary",
  "Indonesia",
  "India",
  "Ireland",
  "Iran",
  "Iraq",
  "Iceland",
  "Israel",
  "Italy",
  "Jamaica",
  "Jordan",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Kyrgyzstan",
  "Cambodia",
  "South Korea",
  "Kosovo",
  "Kuwait",
  "Laos",
  "Lebanon",
  "Liberia",
  "Libya",
  "Sri Lanka",
  "Lesotho",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Morocco",
  "Moldova",
  "Madagascar",
  "Mexico",
  "Macedonia",
  "Mali",
  "Myanmar",
  "Montenegro",
  "Mongolia",
  "Mozambique",
  "Mauritania",
  "Malawi",
  "Malaysia",
  "Namibia",
  "New Caledonia",
  "Niger",
  "Nigeria",
  "Nicaragua",
  "Netherlands",
  "Norway",
  "Nepal",
  "New Zealand",
  "Oman",
  "Pakistan",
  "Panama",
  "Peru",
  "Philippines",
  "Papua New Guinea",
  "Poland",
  "Puerto Rico",
  "North Korea",
  "Portugal",
  "Paraguay",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Western Sahara",
  "Saudi Arabia",
  "Sudan",
  "South Sudan",
  "Senegal",
  "Solomon Islands",
  "Sierra Leone",
  "El Salvador",
  "Somaliland",
  "Somalia",
  "Republic of Serbia",
  "Suriname",
  "Slovakia",
  "Slovenia",
  "Sweden",
  "Swaziland",
  "Syria",
  "Chad",
  "Togo",
  "Thailand",
  "Tajikistan",
  "Turkmenistan",
  "East Timor",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Taiwan",
  "United Republic of Tanzania",
  "Uganda",
  "Ukraine",
  "Uruguay",
  "USA",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Vanuatu",
  "West Bank",
  "Yemen",
  "South Africa",
  "Zambia",
  "Zimbabwe"
]

let getRegion = (country) => {
  if (country == 'Japan')
    return 'JP'
  else if (north_america.includes(country))
    return 'NA'
  else if (europe.includes(country))
    return 'EU'
  else
    return 'Other'
};
